name: Build and Deploy DOcc Documentation

on:
  push:
    branches:
      - main  # Change this to your default branch
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest  # Use your Xcode version

    - name: Build DOcc Documentation
      run: |
        xcodebuild docbuild -scheme Numerica \
        CODE_SIGNING_REQUIRED NO \
        -destination 'platform=iOS Simulator,name=iPhone 14'  # Adjust platform as needed

    - name: Convert to DOcc Archive
      run: |
        DOC_DIR=$(find ~/Library/Developer/Xcode/DerivedData -name "*.doccarchive" | head -n 1)
        mkdir -p docs
        cp -R "$DOC_DIR"/{data,documentation,index} docs/
        touch docs/.nojekyll  # Disable Jekyll on GitHub Pages

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs

